### PR TITLE
Add vmware.log file collection and move network_testbed_setup to test_setup

### LINKED ISSUE #231: [New Feature] Collect vmware.log when test case failed or VM BSOD
##### SUMMARY

Consider collecting vmware.log file when test case failed or only when VM BSOD.

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

Windows

### LINKED ISSUE #264: [New Feature] Consider changing to setup router VM and related configuration when required
##### SUMMARY

Since `network_testbed_setup.yml` is only required in test cases: `['network_device_ops', 'gosc_sanity_staticip', 'gosc_perl_staticip', 'gosc_cloudinit_staticip']`, if set it up at the beginning of the testing, while testing failed at "deploy_vm" or "ovt_verify_install", or the testing is terminated by fatal error or other reasons, the network setup is useless, rerun failure will deploy it again, it's not very effective. We can consider setup network when required due to it's not the requirement of the whole testing. 

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

All

### PR DESCRIPTION
**Pull request by Tomorrow9**
Signed-off-by: dianew <dianew@vmware.com>
Fixes #231 
Fixes #264 

1. add collecting vmware.log in `test_rescue.yml`,
2. move `test_rescue.yml` from Linux and Windows `setup` folder to `common` folder,
3. move 'network_testbed_setup.yml' from `env_setup` to `test_setup` for specific test cases.

### CODE REVIEW

**Comment by Tomorrow9** [comment]
```
VM information:
+------------------------------------------------------------------------------+
| Name                      | test_sles15                                      |
+------------------------------------------------------------------------------+
| IP                        | xx.xx.xx.xx                                     |
+------------------------------------------------------------------------------+
| Guest OS Distribution     | SLES 15.4 x86_64                                 |
+------------------------------------------------------------------------------+
| Hardware Version          | vmx-xx                                          |
+------------------------------------------------------------------------------+
| VMTools Version           | xx.xx.xx                   |
+------------------------------------------------------------------------------+
| CloudInit Version         | 21.2                                             |
+------------------------------------------------------------------------------+
| GUI Installed             | True                                             |
+------------------------------------------------------------------------------+
| Config Guest Id           | sles15_64Guest                                   |
+------------------------------------------------------------------------------+
| GuestInfo Guest Id        | sles15_64Guest                                   |
+------------------------------------------------------------------------------+
| GuestInfo Guest Full Name | SUSE Linux Enterprise 15 (64-bit)                |
+------------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                       |
+------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                               |
|                           | bitness='64'                                     |
|                           | distroName='SLES'                                |
|                           | distroVersion='15.4'                             |
|                           | familyName='Linux'                               |
|                           | kernelVersion='5.14.21-150400.15-default'        |
|                           | prettyName='SUSE Linux Enterprise Server 15 SP4' |
+------------------------------------------------------------------------------+


Test Results (Total: 28, Failed: 0, No Run: 0, Elapsed Time: 02:26:22):
+-----------------------------------------------------------+
| Name                                 | Status | Exec Time |
+-----------------------------------------------------------+
| deploy_vm_efi_nvme_vmxnet3           | Passed | 00:23:25  |
| check_inbox_driver                   | Passed | 00:01:42  |
| ovt_verify_install                   | Passed | 00:10:19  |
| ovt_verify_status                    | Passed | 00:02:43  |
| vgauth_check_service                 | Passed | 00:00:56  |
| check_ip_address                     | Passed | 00:00:49  |
| check_os_fullname                    | Passed | 00:00:46  |
| stat_balloon                         | Passed | 00:00:51  |
| stat_hosttime                        | Passed | 00:00:51  |
| device_list                          | Passed | 00:02:48  |
| check_quiesce_snapshot_custom_script | Passed | 00:01:42  |
| memory_hot_add_basic                 | Passed | 00:06:06  |
| cpu_hot_add_basic                    | Passed | 00:05:04  |
| cpu_multicores_per_socket            | Passed | 00:08:35  |
| check_efi_firmware                   | Passed | 00:00:52  |
| secureboot_enable_disable            | Passed | 00:04:36  |
| e1000e_network_device_ops            | Passed | 00:02:44  |
| vmxnet3_network_device_ops           | Passed | 00:01:51  |
| gosc_perl_dhcp                       | Passed | 00:04:57  |
| gosc_perl_staticip                   | Passed | 00:04:43  |
| gosc_cloudinit_dhcp                  | Passed | 00:09:03  |
| gosc_cloudinit_staticip              | Passed | 00:08:58  |
| paravirtual_vhba_device_ops          | Passed | 00:02:32  |
| lsilogic_vhba_device_ops             | Passed | 00:04:42  |
| lsilogicsas_vhba_device_ops          | Passed | 00:02:24  |
| sata_vhba_device_ops                 | Passed | 00:02:46  |
| nvme_vhba_device_ops                 | Passed | 00:02:23  |
| ovt_verify_uninstall                 | Passed | 00:02:33  |
+-----------------------------------------------------------+
```

**Comment by Tomorrow9** [comment]
```
VM information:
+-----------------------------------------------------------------+
| Name                      | test_photon4_ova                    |
+-----------------------------------------------------------------+
| IP                        | xx.xx.xx.xx                      |
+-----------------------------------------------------------------+
| Guest OS Distribution     | VMware Photon OS 4.0 x86_64         |
+-----------------------------------------------------------------+
| Hardware Version          | vmx-xx                              |
+-----------------------------------------------------------------+
| VMTools Version           | xx.xx.xx      |
+-----------------------------------------------------------------+
| CloudInit Version         | 21.4                                |
+-----------------------------------------------------------------+
| GUI Installed             | False                               |
+-----------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)           |
+-----------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                          |
+-----------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                  |
|                           | bitness='64'                        |
|                           | distroName='VMware Photon OS'       |
|                           | distroVersion='4.0'                 |
|                           | familyName='Linux'                  |
|                           | kernelVersion='5.10.83-6.ph4-esx'   |
|                           | prettyName='VMware Photon OS/Linux' |
+-----------------------------------------------------------------+


Test Results (Total: 28, Failed: 0, No Run: 2, Elapsed Time: 02:13:41):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vmwarephoton_ova              |   Passed | 00:02:38  |
| check_inbox_driver                   |   Passed | 00:06:09  |
| ovt_verify_install                   |   Passed | 00:26:13  |
| ovt_verify_status                    |   Passed | 00:00:48  |
| vgauth_check_service                 |   Passed | 00:00:44  |
| check_ip_address                     |   Passed | 00:00:42  |
| check_os_fullname                    |   Passed | 00:00:38  |
| stat_balloon                         |   Passed | 00:00:34  |
| stat_hosttime                        |   Passed | 00:00:35  |
| device_list                          |   Passed | 00:02:29  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:35  |
| memory_hot_add_basic                 |   Passed | 00:05:17  |
| cpu_hot_add_basic                    |   Passed | 00:04:41  |
| cpu_multicores_per_socket            |   Passed | 00:09:23  |
| check_efi_firmware                   |   Passed | 00:00:44  |
| secureboot_enable_disable            |   Passed | 00:03:55  |
| e1000e_network_device_ops            |   Passed | 00:01:57  |
| vmxnet3_network_device_ops           |   Passed | 00:01:15  |
| gosc_perl_dhcp                       | * No Run | 00:00:38  |
| gosc_perl_staticip                   | * No Run | 00:00:41  |
| gosc_cloudinit_dhcp                  |   Passed | 00:05:21  |
| gosc_cloudinit_staticip              |   Passed | 00:05:38  |
| paravirtual_vhba_device_ops          |   Passed | 00:02:09  |
| lsilogic_vhba_device_ops             |   Passed | 00:02:40  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:02:08  |
| sata_vhba_device_ops                 |   Passed | 00:02:37  |
| nvme_vhba_device_ops                 |   Passed | 00:02:16  |
| ovt_verify_uninstall                 |   Passed | 00:02:43  |
+-------------------------------------------------------------+
```

**Comment by Tomorrow9** [comment]
```
VM information:
+-----------------------------------------------------------------------------------------+
| Name                      | test_vm                                                     |
+-----------------------------------------------------------------------------------------+
| IP                        | xx.xx.xx.xx                                               |
+-----------------------------------------------------------------------------------------+
| Guest OS Distribution     | Microsoft Windows Server 2022 Datacenter                    |
|                           | 10.0.25099.0 64-bit                                         |
+-----------------------------------------------------------------------------------------+
| Hardware Version          | vmx-19                                                      |
+-----------------------------------------------------------------------------------------+
| VMTools Version           | xx.xx.xx                               |
+-----------------------------------------------------------------------------------------+
| GUI Installed             |                                                             |
+-----------------------------------------------------------------------------------------+
| Config Guest Id           | windows2019srvNext_64Guest                                  |
+-----------------------------------------------------------------------------------------+
| GuestInfo Guest Id        | windows2019srvNext_64Guest                                  |
+-----------------------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Microsoft Windows Server 2022 (64-bit)                      |
+-----------------------------------------------------------------------------------------+
| GuestInfo Guest Family    | windowsGuest                                                |
+-----------------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                          |
|                           | bitness='64'                                                |
|                           | buildNumber='25099'                                         |
|                           | distroName='Windows'                                        |
|                           | distroVersion='10.0'                                        |
|                           | familyName='Windows'                                        |
|                           | kernelVersion='25099.1000'                                  |
|                           | prettyName='Windows Server 2022, 64-bit (Build 25099.1000)' |
+-----------------------------------------------------------------------------------------+


Test Results (Total: 23, Failed: 2, No Run: 0, Elapsed Time: 02:13:12):
+---------------------------------------------------------+
| Name                             |   Status | Exec Time |
+---------------------------------------------------------+
| deploy_vm_efi_nvme_e1000e        |   Passed | 00:11:41  |
| check_inbox_driver               |   Passed | 00:03:00  |
| secureboot_enable_disable        |   Passed | 00:03:40  |
| wintools_complete_install_verify |   Passed | 00:05:54  |
| check_efi_firmware               |   Passed | 00:00:46  |
| check_ip_address                 |   Passed | 00:00:47  |
| check_os_fullname                |   Passed | 00:00:36  |
| mouse_driver_vmtools             |   Passed | 00:00:36  |
| vgauth_check_service             |   Passed | 00:00:32  |
| stat_balloon                     |   Passed | 00:00:40  |
| paravirtual_vhba_device_ops      |   Passed | 00:03:42  |
| lsilogicsas_vhba_device_ops      |   Passed | 00:03:36  |
| sata_vhba_device_ops             |   Passed | 00:03:44  |
| nvme_vhba_device_ops             |   Passed | 00:05:22  |
| e1000e_network_device_ops        |   Passed | 00:04:47  |
| vmxnet3_network_device_ops       |   Passed | 00:03:45  |
| memory_hot_add_basic             |   Passed | 00:09:30  |
| check_quiesce_snapshot           | * Failed | 00:00:29  |
| cpu_multicores_per_socket        |   Passed | 00:06:49  |
| gosc_sanity_staticip             |   Passed | 00:05:37  |
| gosc_sanity_dhcp                 |   Passed | 00:07:34  |
| wintools_uninstall_verify        |   Passed | 00:02:57  |
| cpu_hot_add_basic                | * Failed | 00:11:35  |
+---------------------------------------------------------+
```

**Review by keirazhang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
