### PR TITLE
Fix #284 Update quiesce snapshot scripts for Linux

### LINKED ISSUE #284: [Bug] [Debian] check_quiesce_snapshot_custom_script failed on 32bit Debian
##### SUMMARY

The quiesce snapshot scripts are ELF 64-bit LSB executables, which can't be executed on 32bit Debian.
```
2022-03-08 05:00:37,008 | Failed at Play [check_quiesce_snapshot_custom_script] ******

2022-03-08 05:00:37,008 | TASK [Create snapshot 'quiesce_snapshot_2022-03-08-05-00-33' on 'test_vm-2'] 
task path: /home/worker/workspace/Ansible_Debian_11.x_32bit_MAIN_PARAVIRTUAL_E1000E_BIOS/ansible-vsphere-gos-validation/common/vm_take_snapshot.yml:4
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "ansible_test",
            "description": "",
            "folder": "/ansible_test/vm",
            "hostname": "10.186.204.197",
            "memory_dump": false,
            "moid": null,
            "name": "test_vm-2",
            "name_match": "first",
            "new_description": null,
            "new_snapshot_name": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "quiesce": true,
            "remove_children": false,
            "snapshot_name": "quiesce_snapshot_2022-03-08-05-00-33",
            "state": "present",
            "use_instance_uuid": false,
            "username": "[Administrator@vsphere.local](mailto:Administrator@vsphere.local)",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "An error occurred while quiescing the virtual machine. See the virtual machine's event log for details."
}
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below



```

##### CONFIGURATION

```paste below



```

##### ENVIRONMENT / OS

Debian 10.x 32bit
Debian 11.x 32bit

### PR DESCRIPTION
**Pull request by keirazhang**
Fix #284 add 32bit quiesce snapshot script

### CODE REVIEW

**Review by Tomorrow9 — DISMISSED** [review]
LGTM, thanks!

**Comment by keirazhang** [comment]
Tested with Flatcar 3033.2.0
```
+---------------------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                                              |
|                           | bitness='64'                                                    |
|                           | buildNumber='2021-12-10-1820'                                   |
|                           | distroName='Flatcar Container Linux by Kinvolk'                 |
|                           | distroVersion='3033.2.0'                                        |
|                           | familyName='Linux'                                              |
|                           | kernelVersion='5.10.84-flatcar'                                 |
|                           | prettyName='Flatcar Container Linux by Kinvolk 3033.2.0 (Oklo)' |
+---------------------------------------------------------------------------------------------+


Test Results (Total: 1, Failed: 0, No Run: 0, Elapsed Time: 00:01:26):
+-----------------------------------------------------------+
| Name                                 | Status | Exec Time |
+-----------------------------------------------------------+
| check_quiesce_snapshot_custom_script | Passed | 00:01:09  |
+-----------------------------------------------------------+
```
Tested with Debian 11.3 (32bit)
```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.3 i386                            |
+-------------------------------------------------------------------------+
| GuestInfo Detailed Data   | bitness='32'                                |
|                           | distroName='Debian'                         |
|                           | distroVersion='11'                          |
|                           | familyName='Linux'                          |
|                           | kernelVersion='5.10.0-13-686-pae'           |
|                           | prettyName='Debian GNU/Linux 11 (bullseye)' |
+-------------------------------------------------------------------------+

+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| check_quiesce_snapshot_custom_script |   Passed | 00:01:33  |
+-------------------------------------------------------------+
```

**Comment by keirazhang** [comment]
Tested with Debian 11.3 (64bit) 
```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.3 x86_64                          |
+-------------------------------------------------------------------------+
| GuestInfo Detailed Data   | bitness='64'                                |
|                           | distroName='Debian'                         |
|                           | distroVersion='11'                          |
|                           | familyName='Linux'                          |
|                           | kernelVersion='5.10.0-13-amd64'             |
|                           | prettyName='Debian GNU/Linux 11 (bullseye)' |
+-------------------------------------------------------------------------+


Test Results (Total: 1, Failed: 0, No Run: 0, Elapsed Time: 00:01:24):
+-----------------------------------------------------------+
| Name                                 | Status | Exec Time |
+-----------------------------------------------------------+
| check_quiesce_snapshot_custom_script | Passed | 00:01:06  |
+-----------------------------------------------------------+
```

**Review by Tomorrow9 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
