### PR TITLE
Add Astra Linux support

### PR DESCRIPTION
**Pull request by bl33d**
Hello.
This is an adaptation of tests for the Astra Linux Orel distro (https://astralinux.ru/).

Image for tests - https://nas01.astralinux.ru/sharing/wJss3PxqA

```
Testbed information:
+-------------------------------------------------------------+
| Product | Version | Build    | Hostname or IP               |
+-------------------------------------------------------------+
| vCenter | 7.0.2   | 17694817 | vcsa01.stand01.astralinux.ru |
+-------------------------------------------------------------+
| ESXi    | 7.0.2   | 17867351 | esxi.astratest.local         |
+-------------------------------------------------------------+

VM information:
+------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                 |
+------------------------------------------------------------------------+
| VMTools Version           | 11.3.0.29534 (build-18090558)              |
+------------------------------------------------------------------------+
| IP                        | ip here                           |
+------------------------------------------------------------------------+
| GuestInfo Guest Id        | other5xLinux64Guest                        |
+------------------------------------------------------------------------+
| Hardware Version          | vmx-19                                     |
+------------------------------------------------------------------------+
| Guest OS Type             | Astra Linux (Orel) 2.12.43 x86_64          |
+------------------------------------------------------------------------+
| CloudInit Version         |                                            |
+------------------------------------------------------------------------+
| Config Guest Id           | other5xLinux64Guest                        |
+------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Other 5.x or later Linux (64-bit)          |
+------------------------------------------------------------------------+
| Name                      | DEPLOY_VM_5.4_TEST                         |
+------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                         |
|                           | bitness='64'                               |
|                           | distroName='AstraLinuxCE'                  |
|                           | distroVersion='2.12.43'                    |
|                           | familyName='Linux'                         |
|                           | kernelVersion='5.4.0-71-generic'           |
|                           | prettyName='Astra Linux CE 2.12.43 (Orel)' |
+------------------------------------------------------------------------+

Test Results (Total: 28, Failed: 0, No Run: 5, Elapsed Time: 01:23:23):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_ova                           |   Passed | 00:03:25  |
| ovt_verify_install                   |   Passed | 00:06:51  |
| ovt_verify_status                    |   Passed | 00:03:00  |
| vgauth_check_service                 |   Passed | 00:00:56  |
| check_ip_address                     |   Passed | 00:01:00  |
| stat_balloon                         |   Passed | 00:00:45  |
| stat_hosttime                        |   Passed | 00:00:51  |
| check_inbox_driver                   |   Passed | 00:01:05  |
| check_os_fullname                    |   Passed | 00:01:00  |
| check_efi_firmware                   |   Passed | 00:00:56  |
| cpu_hot_add_basic                    |   Passed | 00:05:21  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:36  |
| memory_hot_add_basic                 |   Passed | 00:06:24  |
| device_list                          |   Passed | 00:03:24  |
| secureboot_enable_disable            | * No Run | 00:01:00  |
| e1000e_network_device_ops            |   Passed | 00:01:36  |
| vmxnet3_network_device_ops           |   Passed | 00:01:40  |
| cpu_multicores_per_socket            |   Passed | 00:11:36  |
| gosc_perl_dhcp                       | * No Run | 00:00:54  |
| gosc_perl_staticip                   | * No Run | 00:00:48  |
| gosc_cloudinit_dhcp                  | * No Run | 00:00:52  |
| gosc_cloudinit_staticip              | * No Run | 00:00:46  |
| paravirtual_vhba_device_ops          |   Passed | 00:04:06  |
| lsilogic_vhba_device_ops             |   Passed | 00:04:59  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:04:12  |
| sata_vhba_device_ops                 |   Passed | 00:04:30  |
| nvme_vhba_device_ops                 |   Passed | 00:02:31  |
| ovt_verify_uninstall                 |   Passed | 00:03:51  |
+-------------------------------------------------------------+
```

### CODE REVIEW

**Comment by bl33d** [comment]
Updated the first message in PR, added the necessary information there.

Sorry for the noise with git push, didn't work with --signoff before.

**Review by keirazhang — DISMISSED** [review]

**Comment by bl33d** [comment]
Rebased on main

**Review by Tomorrow9 — APPROVED** [review]
LGTM, thanks for the contribution.

**Review by keirazhang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
