### PR TITLE
Support Debian  10.x and 11.x Autoinstall

### PR DESCRIPTION
**Pull request by keirazhang**
This change will support Debian 10.10 and later, and Debian 11.x autointsall.

### CODE REVIEW

**Comment by keirazhang** [comment]
Tested with Photon 4.0 Rev2 on BIOS and UEFI mode
```
+-----------------------------------------------------------------+
| VMTools Version           | 11.3.5.31214 (build-18557794)       |
+-----------------------------------------------------------------+
| CloudInit Version         | 21.4                                |
+-----------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)           |
+-----------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                          |
+-----------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                  |
|                           | bitness='64'                        |
|                           | distroName='VMware Photon OS'       |
|                           | distroVersion='4.0'                 |
|                           | familyName='Linux'                  |
|                           | kernelVersion='5.10.83-7.ph4-esx'   |
|                           | prettyName='VMware Photon OS/Linux' |
+-----------------------------------------------------------------+


Test Results (Total: 28, Failed: 0, No Run: 2, Elapsed Time: 01:59:40):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_bios_paravirtual_vmxnet3   |   Passed | 00:07:55  |
| ovt_verify_install                   |   Passed | 00:06:24  |
| ovt_verify_status                    |   Passed | 00:01:06  |
| vgauth_check_service                 |   Passed | 00:01:05  |
| check_ip_address                     |   Passed | 00:00:57  |
| stat_balloon                         |   Passed | 00:01:00  |
| stat_hosttime                        |   Passed | 00:01:00  |
| check_inbox_driver                   |   Passed | 00:01:07  |
| check_os_fullname                    |   Passed | 00:01:03  |
| check_efi_firmware                   | * No Run | 00:00:58  |
| cpu_hot_add_basic                    |   Passed | 00:04:41  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:44  |
| memory_hot_add_basic                 |   Passed | 00:05:47  |
| device_list                          |   Passed | 00:02:49  |
| secureboot_enable_disable            | * No Run | 00:00:57  |
| e1000e_network_device_ops            |   Passed | 00:01:26  |
| vmxnet3_network_device_ops           |   Passed | 00:01:30  |
| cpu_multicores_per_socket            |   Passed | 00:09:11  |
| gosc_perl_dhcp                       |   Passed | 00:05:35  |
| gosc_perl_staticip                   |   Passed | 00:05:23  |
| gosc_cloudinit_dhcp                  |   Passed | 00:05:28  |
| gosc_cloudinit_staticip              |   Passed | 00:05:24  |
| paravirtual_vhba_device_ops          |   Passed | 00:02:29  |
| lsilogic_vhba_device_ops             |   Passed | 00:02:55  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:02:24  |
| sata_vhba_device_ops                 |   Passed | 00:02:50  |
| nvme_vhba_device_ops                 |   Passed | 00:02:27  |
| ovt_verify_uninstall                 |   Passed | 00:02:54  |
+-------------------------------------------------------------+
```

```
+-----------------------------------------------------------------+
| CloudInit Version         | 21.4                                |
+-----------------------------------------------------------------+
| Config Guest Id           | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Id        | vmwarePhoton64Guest                 |
+-----------------------------------------------------------------+
| GuestInfo Guest Full Name | VMware Photon OS (64-bit)           |
+-----------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                          |
+-----------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                  |
|                           | bitness='64'                        |
|                           | distroName='VMware Photon OS'       |
|                           | distroVersion='4.0'                 |
|                           | familyName='Linux'                  |
|                           | kernelVersion='5.10.83-7.ph4-esx'   |
|                           | prettyName='VMware Photon OS/Linux' |
+-----------------------------------------------------------------+


Test Results (Total: 28, Failed: 0, No Run: 0, Elapsed Time: 02:15:06):
+-----------------------------------------------------------+
| Name                                 | Status | Exec Time |
+-----------------------------------------------------------+
| deploy_vm_efi_nvme_e1000e            | Passed | 00:08:11  |
| ovt_verify_install                   | Passed | 00:06:35  |
| ovt_verify_status                    | Passed | 00:01:11  |
| vgauth_check_service                 | Passed | 00:00:31  |
| check_ip_address                     | Passed | 00:00:31  |
| stat_balloon                         | Passed | 00:00:33  |
| stat_hosttime                        | Passed | 00:00:35  |
| check_inbox_driver                   | Passed | 00:00:45  |
| check_os_fullname                    | Passed | 00:00:34  |
| check_efi_firmware                   | Passed | 00:00:38  |
| cpu_hot_add_basic                    | Passed | 00:04:23  |
| check_quiesce_snapshot_custom_script | Passed | 00:01:28  |
| memory_hot_add_basic                 | Passed | 00:05:19  |
| device_list                          | Passed | 00:02:24  |
| secureboot_enable_disable            | Passed | 00:03:51  |
| e1000e_network_device_ops            | Passed | 00:01:12  |
| vmxnet3_network_device_ops           | Passed | 00:01:04  |
| cpu_multicores_per_socket            | Passed | 00:08:19  |
| gosc_perl_dhcp                       | Passed | 00:05:25  |
| gosc_perl_staticip                   | Passed | 00:05:16  |
| gosc_cloudinit_dhcp                  | Passed | 00:05:35  |
| gosc_cloudinit_staticip              | Passed | 00:05:05  |
| paravirtual_vhba_device_ops          | Passed | 00:01:57  |
| lsilogic_vhba_device_ops             | Passed | 00:02:21  |
| lsilogicsas_vhba_device_ops          | Passed | 00:01:54  |
| sata_vhba_device_ops                 | Passed | 00:02:16  |
| nvme_vhba_device_ops                 | Passed | 00:01:51  |
| ovt_verify_uninstall                 | Passed | 00:02:39  |
+-----------------------------------------------------------+
```

**Comment by keirazhang** [comment]
Tested with Debian 11.0 32bit and 64bit image. Cloud-init GOSC failure is OS issue, which has been fixed in cloud-init 22.1.
```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.0 i386                            |
+-------------------------------------------------------------------------+
| VMTools Version           | 11.2.5.26209 (build-17337674)               |
+-------------------------------------------------------------------------+
| CloudInit Version         | 20.4.1-2+deb11u1                            |
+-------------------------------------------------------------------------+
| Config Guest Id           | debian11Guest                               |
+-------------------------------------------------------------------------+
| GuestInfo Guest Id        | debian11Guest                               |
+-------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Debian GNU/Linux 11 (32-bit)                |
+-------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                  |
+-------------------------------------------------------------------------+
| GuestInfo Detailed Data   | bitness='32'                                |
|                           | distroName='Debian'                         |
|                           | distroVersion='11'                          |
|                           | familyName='Linux'                          |
|                           | kernelVersion='5.10.0-8-686-pae'            |
|                           | prettyName='Debian GNU/Linux 11 (bullseye)' |
+-------------------------------------------------------------------------+


Test Results (Total: 28, Failed: 4, No Run: 2, Elapsed Time: 02:07:36):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_bios_paravirtual_e1000e    |   Passed | 00:19:45  |
| ovt_verify_install                   |   Passed | 00:05:43  |
| ovt_verify_status                    |   Passed | 00:02:47  |
| vgauth_check_service                 |   Passed | 00:00:58  |
| check_ip_address                     |   Passed | 00:00:57  |
| stat_balloon                         |   Passed | 00:00:57  |
| stat_hosttime                        |   Passed | 00:01:03  |
| check_inbox_driver                   |   Passed | 00:01:06  |
| check_os_fullname                    |   Passed | 00:01:04  |
| check_efi_firmware                   | * No Run | 00:00:53  |
| cpu_hot_add_basic                    |   Passed | 00:04:41  |
| check_quiesce_snapshot_custom_script | * Failed | 00:01:08  |
| memory_hot_add_basic                 | * Failed | 00:02:46  |
| device_list                          |   Passed | 00:02:58  |
| secureboot_enable_disable            | * No Run | 00:01:02  |
| e1000e_network_device_ops            |   Passed | 00:01:37  |
| vmxnet3_network_device_ops           |   Passed | 00:01:39  |
| cpu_multicores_per_socket            |   Passed | 00:09:20  |
| gosc_perl_dhcp                       |   Passed | 00:04:56  |
| gosc_perl_staticip                   |   Passed | 00:04:22  |
| gosc_cloudinit_dhcp                  | * Failed | 00:09:37  |
| gosc_cloudinit_staticip              | * Failed | 00:09:35  |
| paravirtual_vhba_device_ops          |   Passed | 00:01:56  |
| lsilogic_vhba_device_ops             |   Passed | 00:04:35  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:01:51  |
| sata_vhba_device_ops                 |   Passed | 00:02:07  |
| nvme_vhba_device_ops                 |   Passed | 00:01:54  |
| ovt_verify_uninstall                 |   Passed | 00:02:58  |
+-------------------------------------------------------------+
```

```
+-------------------------------------------------------------------------+
| Guest OS Distribution     | Debian 11.0 x86_64                          |
+-------------------------------------------------------------------------+
| VMTools Version           | 11.2.5.26209 (build-17337674)               |
+-------------------------------------------------------------------------+
| CloudInit Version         | 20.4.1-2+deb11u1                            |
+-------------------------------------------------------------------------+
| Config Guest Id           | debian11_64Guest                            |
+-------------------------------------------------------------------------+
| GuestInfo Guest Id        | debian11_64Guest                            |
+-------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Debian GNU/Linux 11 (64-bit)                |
+-------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                  |
+-------------------------------------------------------------------------+
| GuestInfo Detailed Data   | bitness='64'                                |
|                           | distroName='Debian'                         |
|                           | distroVersion='11'                          |
|                           | familyName='Linux'                          |
|                           | kernelVersion='5.10.0-8-amd64'              |
|                           | prettyName='Debian GNU/Linux 11 (bullseye)' |
+-------------------------------------------------------------------------+


Test Results (Total: 28, Failed: 2, No Run: 0, Elapsed Time: 01:42:50):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_efi_paravirtual_vmxnet3    |   Passed | 00:18:11  |
| ovt_verify_install                   |   Passed | 00:05:22  |
| ovt_verify_status                    |   Passed | 00:02:20  |
| vgauth_check_service                 |   Passed | 00:00:38  |
| check_ip_address                     |   Passed | 00:00:34  |
| stat_balloon                         |   Passed | 00:00:29  |
| stat_hosttime                        |   Passed | 00:00:31  |
| check_inbox_driver                   |   Passed | 00:00:37  |
| check_os_fullname                    |   Passed | 00:00:32  |
| check_efi_firmware                   |   Passed | 00:00:41  |
| cpu_hot_add_basic                    |   Passed | 00:04:10  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:24  |
| memory_hot_add_basic                 |   Passed | 00:05:17  |
| device_list                          |   Passed | 00:02:21  |
| secureboot_enable_disable            |   Passed | 00:03:51  |
| e1000e_network_device_ops            |   Passed | 00:01:08  |
| vmxnet3_network_device_ops           |   Passed | 00:01:11  |
| cpu_multicores_per_socket            |   Passed | 00:08:43  |
| gosc_perl_dhcp                       |   Passed | 00:04:23  |
| gosc_perl_staticip                   |   Passed | 00:04:03  |
| gosc_cloudinit_dhcp                  | * Failed | 00:09:09  |
| gosc_cloudinit_staticip              | * Failed | 00:08:59  |
| paravirtual_vhba_device_ops          |   Passed | 00:02:06  |
| lsilogic_vhba_device_ops             |   Passed | 00:04:38  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:02:02  |
| sata_vhba_device_ops                 |   Passed | 00:02:09  |
| nvme_vhba_device_ops                 |   Passed | 00:01:59  |
| ovt_verify_uninstall                 |   Passed | 00:02:36  |
+-------------------------------------------------------------+
```

**Comment by keirazhang** [comment]
Tested with Debian 10.10 32bit and 64bit image, same issue with Debian 11.0
```
+------------------------------------------------------------+
| Guest OS Distribution     | Debian 10.10 i386              |
+------------------------------------------------------------+
| VMTools Version           | 10.3.10.10540 (build-12406962) |
+------------------------------------------------------------+
| CloudInit Version         | 20.2-2~deb10u2                 |
+------------------------------------------------------------+
| Config Guest Id           | debian10Guest                  |
+------------------------------------------------------------+
| GuestInfo Guest Id        | debian10Guest                  |
+------------------------------------------------------------+
| GuestInfo Guest Full Name | Debian GNU/Linux 10 (32-bit)   |
+------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                     |
+------------------------------------------------------------+
| GuestInfo Detailed Data   |                                |
+------------------------------------------------------------+


Test Results (Total: 28, Failed: 3, No Run: 1, Elapsed Time: 01:50:37):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_efi_nvme_vmxnet3           |   Passed | 00:20:28  |
| ovt_verify_install                   |   Passed | 00:06:08  |
| ovt_verify_status                    |   Passed | 00:02:55  |
| vgauth_check_service                 |   Passed | 00:00:52  |
| check_ip_address                     |   Passed | 00:00:58  |
| stat_balloon                         |   Passed | 00:00:54  |
| stat_hosttime                        |   Passed | 00:00:51  |
| check_inbox_driver                   |   Passed | 00:01:08  |
| check_os_fullname                    |   Passed | 00:00:58  |
| check_efi_firmware                   |   Passed | 00:00:59  |
| cpu_hot_add_basic                    |   Passed | 00:05:41  |
| check_quiesce_snapshot_custom_script | * Failed | 00:01:08  |
| memory_hot_add_basic                 | * No Run | 00:02:46  |
| device_list                          |   Passed | 00:02:57  |
| secureboot_enable_disable            |   Passed | 00:04:26  |
| e1000e_network_device_ops            |   Passed | 00:01:36  |
| vmxnet3_network_device_ops           |   Passed | 00:01:41  |
| cpu_multicores_per_socket            |   Passed | 00:09:42  |
| gosc_perl_dhcp                       |   Passed | 00:04:55  |
| gosc_perl_staticip                   |   Passed | 00:04:39  |
| gosc_cloudinit_dhcp                  | * Failed | 00:08:54  |
| gosc_cloudinit_staticip              | * Failed | 00:08:44  |
| paravirtual_vhba_device_ops          |   Passed | 00:01:53  |
| lsilogic_vhba_device_ops             |   Passed | 00:02:36  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:01:58  |
| sata_vhba_device_ops                 |   Passed | 00:02:16  |
| nvme_vhba_device_ops                 |   Passed | 00:01:56  |
| ovt_verify_uninstall                 |   Passed | 00:02:51  |
+-------------------------------------------------------------+
```
```
+------------------------------------------------------------+
| Guest OS Distribution     | Debian 10.10 x86_64            |
+------------------------------------------------------------+
| VMTools Version           | 10.3.10.10540 (build-12406962) |
+------------------------------------------------------------+
| CloudInit Version         | 20.2-2~deb10u2                 |
+------------------------------------------------------------+
| Config Guest Id           | debian10_64Guest               |
+------------------------------------------------------------+
| GuestInfo Guest Id        | debian10_64Guest               |
+------------------------------------------------------------+
| GuestInfo Guest Full Name | Debian GNU/Linux 10 (64-bit)   |
+------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                     |
+------------------------------------------------------------+
| GuestInfo Detailed Data   |                                |
+------------------------------------------------------------+


Test Results (Total: 28, Failed: 2, No Run: 2, Elapsed Time: 02:16:46):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_bios_nvme_e1000e           |   Passed | 00:41:04  |
| ovt_verify_install                   |   Passed | 00:06:18  |
| ovt_verify_status                    |   Passed | 00:03:08  |
| vgauth_check_service                 |   Passed | 00:00:51  |
| check_ip_address                     |   Passed | 00:00:53  |
| stat_balloon                         |   Passed | 00:00:49  |
| stat_hosttime                        |   Passed | 00:00:59  |
| check_inbox_driver                   |   Passed | 00:01:12  |
| check_os_fullname                    |   Passed | 00:00:49  |
| check_efi_firmware                   | * No Run | 00:00:49  |
| cpu_hot_add_basic                    |   Passed | 00:05:13  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:44  |
| memory_hot_add_basic                 |   Passed | 00:06:18  |
| device_list                          |   Passed | 00:03:04  |
| secureboot_enable_disable            | * No Run | 00:00:48  |
| e1000e_network_device_ops            |   Passed | 00:01:39  |
| vmxnet3_network_device_ops           |   Passed | 00:01:35  |
| cpu_multicores_per_socket            |   Passed | 00:10:57  |
| gosc_perl_dhcp                       |   Passed | 00:04:55  |
| gosc_perl_staticip                   |   Passed | 00:04:45  |
| gosc_cloudinit_dhcp                  | * Failed | 00:09:51  |
| gosc_cloudinit_staticip              | * Failed | 00:09:38  |
| paravirtual_vhba_device_ops          |   Passed | 00:02:25  |
| lsilogic_vhba_device_ops             |   Passed | 00:03:07  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:02:23  |
| sata_vhba_device_ops                 |   Passed | 00:02:51  |
| nvme_vhba_device_ops                 |   Passed | 00:02:31  |
| ovt_verify_uninstall                 |   Passed | 00:03:00  |
+-------------------------------------------------------------+
```

**Review by Tomorrow9 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
