### PR TITLE
Support to test RHEL 9.0 perl GOSC on VC 6.7 Update 3r

### PR DESCRIPTION
**Pull request by keirazhang**
Signed-off-by: Qi Zhang <qiz@vmware.com>

### CODE REVIEW

**Comment by keirazhang** [comment]
```
Testbed information:
+------------------------------------------------------+
| Product | Version        | Build    | Hostname or IP |
+------------------------------------------------------+
| vCenter | 6.7.0          | 19832280 |                |
+------------------------------------------------------+
| ESXi    | 6.7.0 Update 3 | 19898918 |                |
+------------------------------------------------------+


VM information:
+------------------------------------------------------------------------------+
| Name                      | test_rhel9                                       |
+------------------------------------------------------------------------------+
| Guest OS Distribution     | RedHat 9.0 x86_64                                |
+------------------------------------------------------------------------------+
| Hardware Version          | vmx-14                                           |
+------------------------------------------------------------------------------+
| VMTools Version           | 11.3.5 (build-18557794)                          |
+------------------------------------------------------------------------------+
| CloudInit Version         | 21.1                                             |
+------------------------------------------------------------------------------+
| GUI Installed             | True                                             |
+------------------------------------------------------------------------------+
| Config Guest Id           | rhel8_64Guest                                    |
+------------------------------------------------------------------------------+
| GuestInfo Guest Id        | rhel8_64Guest                                    |
+------------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Red Hat Enterprise Linux 8 (64-bit)              |
+------------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                       |
+------------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                               |
|                           | bitness='64'                                     |
|                           | distroName='Red Hat Enterprise Linux'            |
|                           | distroVersion='9.0'                              |
|                           | familyName='Linux'                               |
|                           | kernelVersion='5.14.0-70.13.1.el9_0.x86_64'      |
|                           | prettyName='Red Hat Enterprise Linux 9.0 (Plow)' |
+------------------------------------------------------------------------------+


Test Results (Total: 3, Passed: 3, Elapsed Time: 00:56:13)
+-----------------------------------------------------+
| Name                           | Status | Exec Time |
+-----------------------------------------------------+
| deploy_vm_efi_lsilogic_vmxnet3 | Passed | 00:41:54  |
| gosc_perl_dhcp                 | Passed | 00:06:35  |
| gosc_perl_staticip             | Passed | 00:06:33  |
+-----------------------------------------------------+
```

**Comment by keirazhang** [comment]
```
Testbed information:
+-----------------------------------------------+
| Product | Version | Build    | Hostname or IP |
+-----------------------------------------------+
| vCenter | 7.0.3   | 19480866 | 
+-----------------------------------------------+
| ESXi    | 7.0.3   | 19482537 | 
+-----------------------------------------------+


VM information:
+-----------------------------------------------------------------------+
| Name                      | test_almalinux8                           |
+-----------------------------------------------------------------------+
| Guest OS Distribution     | AlmaLinux 8.6 x86_64                      |
+-----------------------------------------------------------------------+
| Hardware Version          | vmx-19                                    |
+-----------------------------------------------------------------------+
| VMTools Version           | 11.3.5 (build-18557794)                   |
+-----------------------------------------------------------------------+
| CloudInit Version         | 21.1                                      |
+-----------------------------------------------------------------------+
| GUI Installed             | True                                      |
+-----------------------------------------------------------------------+
| Config Guest Id           | other4xLinux64Guest                       |
+-----------------------------------------------------------------------+
| GuestInfo Guest Id        | other4xLinux64Guest                       |
+-----------------------------------------------------------------------+
| GuestInfo Guest Full Name | Other 4.x Linux (64-bit)                  |
+-----------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                |
+-----------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                        |
|                           | bitness='64'                              |
|                           | distroName='AlmaLinux'                    |
|                           | distroVersion='8.6'                       |
|                           | familyName='Linux'                        |
|                           | kernelVersion='4.18.0-372.9.1.el8.x86_64' |
|                           | prettyName='AlmaLinux 8.6 (Sky Tiger)'    |
+-----------------------------------------------------------------------+


Test Results (Total: 3, Passed: 3, Elapsed Time: 02:03:53)
+--------------------------------------------------------+
| Name                              | Status | Exec Time |
+--------------------------------------------------------+
| deploy_vm_efi_paravirtual_vmxnet3 | Passed | 00:30:27  |
| gosc_perl_dhcp                    | Passed | 00:05:45  |
| gosc_perl_staticip                | Passed | 00:05:21  |
+--------------------------------------------------------+
```

**Comment by keirazhang** [comment]
```
Testbed information:
+-----------------------------------------------+
| Product | Version | Build    | Hostname or IP |
+-----------------------------------------------+
| vCenter | 7.0.1   | 16858589 | 
+-----------------------------------------------+
| ESXi    | 7.0.1   | 16850804 | 
+-----------------------------------------------+


VM information:
+----------------------------------------------------------------+
| Name                      | test_ubuntu22.04_iso               |
+----------------------------------------------------------------+
| Guest OS Distribution     | Ubuntu 22.04 x86_64                |
+----------------------------------------------------------------+
| Hardware Version          | vmx-18                             |
+----------------------------------------------------------------+
| VMTools Version           | 11.3.5 (build-18557794)            |
+----------------------------------------------------------------+
| CloudInit Version         | 22.1-14-g2e17a0d6-0ubuntu1~22.04.5 |
+----------------------------------------------------------------+
| GUI Installed             | False                              |
+----------------------------------------------------------------+
| Config Guest Id           | ubuntu64Guest                      |
+----------------------------------------------------------------+
| GuestInfo Guest Id        | ubuntu64Guest                      |
+----------------------------------------------------------------+
| GuestInfo Guest Full Name | Ubuntu Linux (64-bit)              |
+----------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                         |
+----------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                 |
|                           | bitness='64'                       |
|                           | distroName='Ubuntu 22.04 LTS'      |
|                           | distroVersion='22.04'              |
|                           | familyName='Linux'                 |
|                           | kernelVersion='5.15.0-39-generic'  |
|                           | prettyName='Ubuntu 22.04 LTS'      |
+----------------------------------------------------------------+


Test Results (Total: 3, Passed: 3, Elapsed Time: 01:03:47)
+--------------------------------------------------------+
| Name                              | Status | Exec Time |
+--------------------------------------------------------+
| deploy_vm_efi_paravirtual_vmxnet3 | Passed | 00:24:08  |
| gosc_perl_dhcp                    | Passed | 00:06:43  |
| gosc_perl_staticip                | Passed | 00:06:11  |
+--------------------------------------------------------+
```

**Comment by keirazhang** [comment]
```
Testbed information:
+------------------------------------------------------+
| Product | Version        | Build    | Hostname or IP |
+------------------------------------------------------+
| vCenter | 6.7.0          | 18831049 | 
+------------------------------------------------------+
| ESXi    | 6.7.0 Update 3 | 18828794 | 
+------------------------------------------------------+


VM information:
+---------------------------------------------------------------------------+
| Name                      | test_rockylinux8                              |
+---------------------------------------------------------------------------+
| Guest OS Distribution     | Rocky 8.6 x86_64                              |
+---------------------------------------------------------------------------+
| Hardware Version          | vmx-14                                        |
+---------------------------------------------------------------------------+
| VMTools Version           | 11.3.5 (build-18557794)                       |
+---------------------------------------------------------------------------+
| CloudInit Version         | 21.1                                          |
+---------------------------------------------------------------------------+
| GUI Installed             | True                                          |
+---------------------------------------------------------------------------+
| Config Guest Id           | other4xLinux64Guest                           |
+---------------------------------------------------------------------------+
| GuestInfo Guest Id        | other4xLinux64Guest                           |
+---------------------------------------------------------------------------+
| GuestInfo Guest Full Name | Other 4.x or later Linux (64-bit)             |
+---------------------------------------------------------------------------+
| GuestInfo Guest Family    | linuxGuest                                    |
+---------------------------------------------------------------------------+
| GuestInfo Detailed Data   | architecture='X86'                            |
|                           | bitness='64'                                  |
|                           | distroName='Rocky Linux'                      |
|                           | distroVersion='8.6'                           |
|                           | familyName='Linux'                            |
|                           | kernelVersion='4.18.0-372.9.1.el8.x86_64'     |
|                           | prettyName='Rocky Linux 8.6 (Green Obsidian)' |
+---------------------------------------------------------------------------+


Test Results (Total: 3, Passed: 3, Elapsed Time: 01:17:32)
+--------------------------------------------------------+
| Name                              | Status | Exec Time |
+--------------------------------------------------------+
| deploy_vm_efi_paravirtual_vmxnet3 | Passed | 00:39:47  |
| gosc_perl_dhcp                    | Passed | 00:06:26  |
| gosc_perl_staticip                | Passed | 00:06:33  |
+--------------------------------------------------------+
```

**Review by Tomorrow9 — APPROVED** [review]
LGTM, thanks~

**Pull request merged**
