### PR TITLE
[Kylin Server] support autointall for Kylin server V10

### PR DESCRIPTION
**Pull request by ZouYuhua**
Support autointall for Kylin server V10.

test result:
image

### CODE REVIEW

**Review by keirazhang — CHANGES_REQUESTED** [review]

**Comment by keirazhang** [comment]
`linux/deploy_vm/deploy_vm_from_iso.yml` and `README.md` should also be updated. And please run all of linux test cases to support as many cases as we can, not just autoinstall.

**Comment by ZouYuhua** [comment]
Passed without open-vm-tools installed:
image

**Comment by ZouYuhua** [comment]
> `linux/deploy_vm/deploy_vm_from_iso.yml` and `README.md` should also be updated. And please run all of linux test cases to support as many cases as we can, not just autoinstall.

Is it OK the support ansible testcases in other ticket and then modify README.md file to declare supporting it ?    Thanks

**Comment by ZouYuhua** [comment]
New merge request https://github.com/vmware/ansible-vsphere-gos-validation/pull/534 for this task.
to void worning message about unsigned commit from rebase.

**Comment by ZouYuhua** [comment]
New merge request https://github.com/vmware/ansible-vsphere-gos-validation/pull/534 for this task.
to void worning message about unsigned commit from rebase.

**Pull request closed without merging**
