### PR TITLE
Get existing VM info in env_setup and after new VM deploy

### LINKED ISSUE #42: [v1.2][Bug] Get or set VM files related paths variable once
##### SUMMARY

In test cases and common tasks, there are some same tasks to get or set VM datastore path, VM files path, or VM vmware log path, we can set this variable in env_setup once to avoid duplicate tasks.
1. VM datastore path is required to set as the ESXi remote temp path when adding ESXi host to in memory inventory.

2. VM files path is required to transfer seed iso.

3. VM vmware.log file path is required in test cases to check test result.

etc.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]


```

##### CONFIGURATION

```paste below



```

##### ENVIRONMENT / OS

All

### PR DESCRIPTION
**Pull request by Tomorrow9**
Signed-off-by: dianew <dianew@vmware.com>
Fixes #42 

Add a new common task `common/vm_get_vm_info.yml` to get/set:
1. VM datastore
2. VM datatore path
3. VM files path
4. VM vmx file path
5. VM guest ID
6. VM hardware version

### CODE REVIEW

**Comment by Tomorrow9** [comment]
Testing passed on CentOS 8.3
```
VM information:
+-----------------------------------------------------+
| VM Name             | centos-8.3                    |
+-----------------------------------------------------+
| VM IP               | xx.xx.xx.xx                |
+-----------------------------------------------------+
| Guest OS Type       | CentOS 8.3 x86_64             |
+-----------------------------------------------------+
| VM Tools            | 11.2.0.23855 (build-16938113) |
+-----------------------------------------------------+
| Cloud-Init          | 19.4                          |
+-----------------------------------------------------+


Test Results (Total: 28, Failed: 2, No Run: 2, Elapsed Time: 02:05:14):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm_efi_paravirtual_vmxnet3    |   Passed | 00:22:56  |
| ovt_verify_install                   |   Passed | 00:08:42  |
| ovt_verify_status                    |   Passed | 00:03:46  |
| vgauth_check_service                 |   Passed | 00:00:41  |
| check_ip_address                     |   Passed | 00:00:29  |
| stat_balloon                         |   Passed | 00:00:23  |
| stat_hosttime                        |   Passed | 00:00:20  |
| check_inbox_driver                   |   Passed | 00:00:27  |
| check_os_fullname                    |   Passed | 00:00:20  |
| check_efi_firmware                   |   Passed | 00:00:21  |
| cpu_hot_add_basic                    |   Passed | 00:04:31  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:03  |
| memory_hot_add_basic                 |   Passed | 00:06:47  |
| device_list                          |   Passed | 00:03:56  |
| secureboot_enable_disable            |   Passed | 00:06:40  |
| e1000e_network_device_ops            |   Passed | 00:00:55  |
| vmxnet3_network_device_ops           |   Passed | 00:01:02  |
| cpu_multicores_per_socket            |   Passed | 00:10:06  |
| gosc_perl_dhcp                       | * Failed | 00:07:47  |
| gosc_perl_staticip                   | * Failed | 00:07:25  |
| gosc_cloudinit_dhcp                  |   Passed | 00:04:04  |
| gosc_cloudinit_staticip              |   Passed | 00:03:46  |
| paravirtual_vhba_device_ops          |   Passed | 00:01:47  |
| lsilogic_vhba_device_ops             | * No Run | 00:00:22  |
| lsilogicsas_vhba_device_ops          | * No Run | 00:00:18  |
| sata_vhba_device_ops                 |   Passed | 00:02:03  |
| nvme_vhba_device_ops                 |   Passed | 00:02:21  |
| ovt_verify_uninstall                 |   Passed | 00:02:03  |
+-------------------------------------------------------------+
```

**Comment by Tomorrow9** [comment]
Testing passed on Windows ISO installed VM:
```
VM information:
+---------------------------------------------------------------------------+
| VM Name             | 67GA_win_10_64_nvme_bios_ansible                    |
+---------------------------------------------------------------------------+
| VM IP               | xx.xx.xx.xx                                      |
+---------------------------------------------------------------------------+
| Guest OS Type       | Microsoft Windows 10 Enterprise 64-bit |
+---------------------------------------------------------------------------+
| VM Tools            | 10.2.0.1608 (build-7253323)                         |
+---------------------------------------------------------------------------+


Test Results (Total: 22, Failed: 2, No Run: 2, Elapsed Time: 02:25:33):
+---------------------------------------------------------+
| Name                             |   Status | Exec Time |
+---------------------------------------------------------+
| deploy_vm_bios_nvme_e1000e       |   Passed | 00:13:33  |
| secureboot_enable_disable        | * No Run | 00:06:35  |
| wintools_complete_install_verify |   Passed | 00:08:10  |
| check_efi_firmware               | * No Run | 00:00:15  |
| check_ip_address                 |   Passed | 00:00:32  |
| check_os_fullname                |   Passed | 00:00:18  |
| mouse_driver_vmtools             |   Passed | 00:00:20  |
| vgauth_check_service             |   Passed | 00:00:17  |
| stat_balloon                     |   Passed | 00:00:17  |
| paravirtual_vhba_device_ops      |   Passed | 00:04:21  |
| lsilogicsas_vhba_device_ops      |   Passed | 00:04:23  |
| sata_vhba_device_ops             |   Passed | 00:04:19  |
| nvme_vhba_device_ops             | * Failed | 00:04:32  |
| e1000e_network_device_ops        |   Passed | 00:04:21  |
| vmxnet3_network_device_ops       |   Passed | 00:03:28  |
| memory_hot_add_basic             |   Passed | 00:21:26  |
| check_quiesce_snapshot           |   Passed | 00:01:44  |
| cpu_multicores_per_socket        |   Passed | 00:11:07  |
| gosc_sanity_staticip             | * Failed | 00:09:26  |
| gosc_sanity_dhcp                 |   Passed | 00:14:44  |
| wintools_uninstall_verify        |   Passed | 00:06:50  |
| cpu_hot_add_basic                |   Passed | 00:05:30  |
+---------------------------------------------------------+
```

**Comment by Tomorrow9** [comment]
Testing passed on Photon OS ova deploy:
```
VM information:
+-----------------------------------------------------+
| VM Name             | test_vm                       |
+-----------------------------------------------------+
| VM IP               | xx.xx.xx.xx                 |
+-----------------------------------------------------+
| Guest OS Type       | VMware Photon OS 4.0 x86_64   |
+-----------------------------------------------------+
| VM Tools            | 11.3.0.29534 (build-18090558) |
+-----------------------------------------------------+
| Cloud-Init          | 20.4.1                        |
+-----------------------------------------------------+


Test Results (Total: 28, Failed: 3, No Run: 1, Elapsed Time: 01:06:38):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_vm                            | * No Run | 00:00:01  |
| ovt_verify_install                   |   Passed | 00:05:54  |
| ovt_verify_status                    |   Passed | 00:00:36  |
| vgauth_check_service                 |   Passed | 00:00:35  |
| check_ip_address                     |   Passed | 00:00:46  |
| stat_balloon                         |   Passed | 00:00:30  |
| stat_hosttime                        |   Passed | 00:00:29  |
| check_inbox_driver                   |   Passed | 00:00:37  |
| check_os_fullname                    |   Passed | 00:00:40  |
| check_efi_firmware                   |   Passed | 00:00:31  |
| cpu_hot_add_basic                    |   Passed | 00:03:05  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:19  |
| memory_hot_add_basic                 |   Passed | 00:03:48  |
| device_list                          |   Passed | 00:02:15  |
| secureboot_enable_disable            |   Passed | 00:03:40  |
| e1000e_network_device_ops            |   Passed | 00:00:54  |
| vmxnet3_network_device_ops           |   Passed | 00:01:07  |
| cpu_multicores_per_socket            |   Passed | 00:05:13  |
| gosc_perl_dhcp                       | * Failed | 00:04:33  |
| gosc_perl_staticip                   | * Failed | 00:04:19  |
| gosc_cloudinit_dhcp                  |   Passed | 00:04:51  |
| gosc_cloudinit_staticip              |   Passed | 00:04:25  |
| paravirtual_vhba_device_ops          |   Passed | 00:01:42  |
| lsilogic_vhba_device_ops             |   Passed | 00:02:49  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:01:50  |
| sata_vhba_device_ops                 |   Passed | 00:02:08  |
| nvme_vhba_device_ops                 | * Failed | 00:02:00  |
| ovt_verify_uninstall                 |   Passed | 00:02:08  |
+-------------------------------------------------------------+
```

**Comment by Tomorrow9** [comment]
Testing passed on Ubuntu ova deploy:
```
VM information:
+-----------------------------------------------------+
| VM Name             | ubuntu-20.10-ova              |
+-----------------------------------------------------+
| VM IP               | xx.xx.xx.xx                 |
+-----------------------------------------------------+
| Guest OS Type       | Ubuntu 20.10 x86_64           |
+-----------------------------------------------------+
| VM Tools            | 11.2.5.26209 (build-17337674) |
+-----------------------------------------------------+
| Cloud-Init          | 20.3-15-g6d332e5c-0ubuntu1    |
+-----------------------------------------------------+


Test Results (Total: 28, Failed: 2, No Run: 2, Elapsed Time: 01:30:33):
+-------------------------------------------------------------+
| Name                                 |   Status | Exec Time |
+-------------------------------------------------------------+
| deploy_ubuntu_ova                    |   Passed | 00:03:41  |
| ovt_verify_install                   |   Passed | 00:04:36  |
| ovt_verify_status                    |   Passed | 00:00:24  |
| vgauth_check_service                 |   Passed | 00:15:53  |
| check_ip_address                     |   Passed | 00:00:41  |
| stat_balloon                         |   Passed | 00:00:18  |
| stat_hosttime                        |   Passed | 00:00:11  |
| check_inbox_driver                   |   Passed | 00:00:24  |
| check_os_fullname                    |   Passed | 00:00:12  |
| check_efi_firmware                   | * No Run | 00:00:08  |
| cpu_hot_add_basic                    |   Passed | 00:02:35  |
| check_quiesce_snapshot_custom_script |   Passed | 00:01:00  |
| memory_hot_add_basic                 |   Passed | 00:03:30  |
| device_list                          |   Passed | 00:02:01  |
| secureboot_enable_disable            | * No Run | 00:00:15  |
| e1000e_network_device_ops            |   Passed | 00:00:55  |
| vmxnet3_network_device_ops           |   Passed | 00:00:48  |
| cpu_multicores_per_socket            |   Passed | 00:05:55  |
| gosc_perl_dhcp                       |   Passed | 00:03:52  |
| gosc_perl_staticip                   |   Passed | 00:03:41  |
| gosc_cloudinit_dhcp                  | * Failed | 00:03:46  |
| gosc_cloudinit_staticip              |   Passed | 00:03:34  |
| paravirtual_vhba_device_ops          |   Passed | 00:01:39  |
| lsilogic_vhba_device_ops             |   Passed | 00:03:52  |
| lsilogicsas_vhba_device_ops          |   Passed | 00:01:27  |
| sata_vhba_device_ops                 |   Passed | 00:01:46  |
| nvme_vhba_device_ops                 | * Failed | 00:00:23  |
| ovt_verify_uninstall                 |   Passed | 00:02:00  |
+-------------------------------------------------------------+
```

**Review by keirazhang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
