### PR TITLE
[FreeBSD 13] fix ovt_status issue for FreeBSD 13 64bit

### PR DESCRIPTION
**Pull request by ZouYuhua**
Description:
For for FreeBSD 13 64bit, testcase ovt_status is failed as follows:

2024-06-08 03:39:50,008 | Failed at Play [1_ovt_verify_status] ***********************
2024-06-08 03:39:50,008 | TASK [1_ovt_verify_status][Check process 'vmtoolsd -n vmusr' is running] 
task path: /home/worker/workspace/Ansible_Cycle_FreeBSD_13.x_64bit/ansible-vsphere-gos-validation/linux/utils/check_process_status.yml:34
fatal: [localhost]: FAILED! => User 'vmware' doesn't have running process 'vmtoolsd -n vmusr'
error message:
User 'vmware' doesn't have running process 'vmtoolsd -n vmusr'"

Test result:
image

### CODE REVIEW

**Comment by ZouYuhua** [comment]
[WIP:] .....

**Comment by ZouYuhua** [comment]
@keirazhang 
Test pass for this change:

1) For FreeBSD 13.3 64bit:
image

2) For FreeBSD 14 64bit:
image

(Note: I am check the nvme failure in this run)

**Comment by ZouYuhua** [comment]
Passed the testing for change:
1) change   
image
2) test result
image

**Review by keirazhang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
