### PR TITLE
Add getting installed Ansible and collections info

### LINKED ISSUE #90: [New Feature] Collect Ansible version and configure info
##### SUMMARY

When file a new issue, we can provide the Ansible info, collection info and Ansible configure info after adding info collection in the tasks.
```
ansible --version
ansible-galaxy collection list
ansible-config dump --only-changed
```

##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT / OS

All

### PR DESCRIPTION
**Pull request by Tomorrow9**
Signed-off-by: dianew <dianew@vmware.com>
Fixes #90

### CODE REVIEW

**Comment by keirazhang** [comment]
Log plugin prints some ansible information already.

ansible-playbook [core 2.11.1] 
  config file = /root/ansible-vsphere-gos-validation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.1 (default, May 19 2021, 10:27:03) [GCC 10.2.0]
  jinja version = 3.0.1
  libyaml = True
Using /root/ansible-vsphere-gos-validation/ansible.cfg as config file

How about updating the log plugin to print more informatoin about ansible instead of adding a task file? After all, the output of ansible tasks is not friendly for view.

**Comment by Tomorrow9** [comment]
This is the output of the task:
```
TASK [include_tasks] *********************************************************************************************************************
included: /new_disk/ansible-vsphere-gos-validation/env_setup/get_ansible_info.yml for localhost

TASK [Get Ansible version] ***************************************************************************************************************
changed: [localhost]

TASK [Display installed Ansible version info] ********************************************************************************************
ok: [localhost] => {
    "ansible_version_info.stdout_lines": [
        "ansible [core 2.11.2] ",
        "  config file = /etc/ansible/ansible.cfg",
        "  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']",
        "  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible",
        "  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections",
        "  executable location = /usr/local/bin/ansible",
        "  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]",
        "  jinja version = 2.11.2",
        "  libyaml = True"
    ]
}

TASK [Get Ansible collection info] *******************************************************************************************************
changed: [localhost]

TASK [Display installed Ansible collections info] ****************************************************************************************
ok: [localhost] => {
    "ansible_collection_info.stdout_lines": [
        "",
        "# /root/.ansible/collections/ansible_collections",
        "Collection           Version",
        "-------------------- -------",
        "ansible.netcommon    1.4.1  ",
        "ansible.posix        1.1.1  ",
        "ansible.windows      1.7.0  ",
        "community.crypto     1.3.0  ",
        "community.general    1.3.0  ",
        "community.kubernetes 1.1.1  ",
        "community.vmware     1.9.0  ",
        "google.cloud         1.0.1  "
    ]
}

TASK [Get Ansible config change] *********************************************************************************************************
changed: [localhost]

TASK [Display changed Ansible config] ****************************************************************************************************
ok: [localhost] => {
    "ansible_config_info.stdout_lines": []
}
```

**Comment by Tomorrow9** [comment]
I think this output looks fine and this will always be printing at the beginning of the testing, no matter specifying "-vvv" or not at the command line.

**Review by keirazhang — APPROVED** [review]
I see. Then it is OK for me.

**Pull request merged**
